import type { TheoryEntry } from './theory-types'

// 年代按此处可核对的首发版本排列；yearLabel 同时说明后续期刊版本。
// 引文仅采用核对过的短句，正文为结合课程讲义写成的中文解读。
export const modernTheories: TheoryEntry[] = [
  {
    id: 'feldstein-horioka', year: 1979, yearLabel: '1979 工作论文 · 1980 期刊',
    title: '储蓄与投资为何仍紧密相连', authors: 'Martin Feldstein · Charles Horioka',
    originalTitle: 'Domestic Saving and International Capital Flows', kind: 'puzzle',
    question: '资本可以跨境流动，为什么一国投资仍与本国储蓄高度相关？',
    lessonIds: ['globalization', 'accounts'], terms: ['费尔德斯坦—霍里奥卡之谜', '储蓄保留系数', '储蓄与投资'],
    sections: [
      { title: '从开放经济的一个预测开始', paragraphs: ['在完全开放的小型经济中，企业可以向世界市场筹资，居民也可以购买外国资产。国内投资取决于投资回报和世界资金成本，居民储蓄则取决于收入、人口结构与消费选择。因此，储蓄较多的国家不必把这些钱全部投在本国，国内储蓄率与投资率之间不应存在很强的必然联系。', '费尔德斯坦与霍里奥卡用跨国数据检查这项预测。论文先以工作论文形式发表于 1979 年，1980 年发表于《经济学杂志》。它提出的是资本流动程度的经验问题。'] },
      { title: '怎样读储蓄保留系数', paragraphs: ['作者将一国若干年的平均投资率对平均储蓄率作回归。斜率 β 被称为储蓄保留系数：它表示在样本内，储蓄率较高一个百分点的国家，投资率通常高多少个百分点。原研究发现这一系数很高，似乎多数新增储蓄仍留在本国。', '这里比较的是国家之间的长期平均关系。系数为 0.8，并不意味着一笔新增存款中有 80% 被银行明确划拨给国内项目，更不能据此追踪某一笔资金的去向。'] },
      { title: '净流量与总流量', paragraphs: ['经常账户等于储蓄减投资。两者接近，说明跨境净借贷较小；但本国居民购买外国资产和外国居民购买本国资产可以同时很大。一个国家完全可能有庞大的双向资本交易，同时保持近乎平衡的经常账户。', '因此，不能把储蓄—投资相关性直接当作所有金融市场分割的证明。价格能否套利、跨境资产持有规模、净资本流动大小，衡量的是不同方面。'] },
      { title: '相关性还可能从哪里来', paragraphs: ['经济增长、人口年龄结构和财政政策可能同时影响储蓄与投资。大型经济的储蓄变化还会影响世界利率，从而改变自身投资。长期预算约束也使经常账户不能无限累积失衡。遗漏这些因素，会把共同变化误认成资本不能流动。', 'Alan Taylor 在 1994 年的研究中检验了相对价格、增长和人口因素，并发现控制这些变量后，原有相关性明显改变。这说明“相关性来自何处”需要额外识别。'] },
      { title: '与课程中的资本开放相连', paragraphs: ['阅读这项研究时，可以同时观察储蓄率、投资率、经常账户和对外资产负债总额。前两者解释资金缺口，后两者分别呈现净借贷与双向持有。金融开放的程度需要这些证据共同判断。', '即使资本流动自由，居民也可能偏好本国资产；即使国内投资与储蓄同步变化，也不能断言开放没有带来风险分散收益。它与本国偏好之谜、卢卡斯悖论相邻，却各自检验不同的理论预测。'] },
    ],
    sources: [
      { title: '原论文：NBER 工作论文 310', url: 'https://www.nber.org/papers/w0310', note: '1979 年工作论文；1980 年发表于 The Economic Journal。', quote: "How internationally mobile is the world's supply of capital?", translation: '世界资本供给的国际流动性究竟有多大？' },
      { title: '后续检验：Domestic Saving and International Capital Flows Reconsidered', url: 'https://www.nber.org/papers/w4892', note: 'Alan M. Taylor，1994。对共同决定因素与资本市场分割解释的检验。' },
    ],
    formulas: [{ expression: String.raw`\left(\frac{I}{Y}\right)_j=\alpha+\beta\left(\frac{S}{Y}\right)_j+\varepsilon_j`, explanation: 'j 表示国家；I/Y 与 S/Y 为一段时期的平均投资率、储蓄率。β 是统计关系，需要结合识别假设解释。' }],
    related: ['lucas-paradox', 'home-bias', 'intertemporal-account'],
  },
  {
    id: 'intertemporal-account', year: 1981, yearLabel: '1981 · 1994/1995 系统综述',
    title: '经常账户的跨期分析', authors: 'Jeffrey Sachs · Maurice Obstfeld · Kenneth Rogoff',
    originalTitle: 'The Current Account and Macroeconomic Adjustment in the 1970s', kind: 'theory',
    question: '今天的顺差或逆差，怎样反映对未来收入和投资机会的判断？',
    lessonIds: ['accounts', 'globalization'], terms: ['跨期分析', '消费平滑', '跨期预算约束', '经常账户'],
    sections: [
      { title: '石油冲击之后的疑问', paragraphs: ['20 世纪 70 年代，石油输出国积累盈余，不少进口国出现逆差，国际借贷快速扩大。单看当期出口、进口和汇率，难以说明各国为何选择不同的借贷规模。萨克斯在 1981 年的研究中，将居民消费、企业投资和政府支出放进跨期框架。', '奥布斯特费尔德与罗格夫后来系统整理了这一研究传统。其基本问题是：一个国家如何通过今天借入、未来归还，或今天储蓄、未来动用资产，安排不同时期的资源。'] },
      { title: '两期模型的预算约束', paragraphs: ['先设没有政府、投资和初始外债，世界只有一种商品。一国两期收入分别为 Y₁、Y₂，可以按利率 r 借贷。第一期少于收入的消费形成储蓄，第二期得到本金和利息；第一期多消费则须在第二期偿债。', '把两期预算合并，消费现值必须等于收入现值。讲义使用收入为 60、100，利率为零的例子：若居民希望平滑消费，可第一期借入 20，使两期消费均为 80。第一期经常账户为 −20，第二期为 +20。'] },
      { title: '暂时冲击与永久冲击', paragraphs: ['暂时收入下降时，未来偿债能力基本保留，借款可以缓冲当期消费下降。若收入永久减少，未来资源也变少，居民就需要更大幅度地减少消费，逆差未必显著扩大。因此，同样规模的当期收入下降，可能产生不同的经常账户反应。', '新的高回报投资机会也可能带来逆差：企业先进口设备、建设项目，未来产出再偿付借款。观察逆差时，应进一步区分投资扩张、暂时收入下降和持续消费超支。'] },
      { title: '最优选择需要哪些条件', paragraphs: ['基准模型假定居民前瞻、能够借贷，且对未来资源有可用的判断。在边际上，今天少消费一单位的效用损失，等于储蓄后未来多消费的折现效用收益。这就是消费的欧拉条件。', '若借贷受抵押品限制、未来收入高度不确定，或家庭之间收入差异很大，代表性居民模型的预测会改变。居民还可能预防性储蓄；有投资和资本调整成本时，经常账户的动态也更复杂。'] },
      { title: '怎样判断逆差是否可持续', paragraphs: ['跨期预算约束要求未来净收入足以支持今天的负债，但满足会计约束并不保证金融市场愿意继续融资。债务期限、币种、利率和融资渠道都会改变风险。', '跨期分析说明顺差、逆差可以是合理选择，不能据此宣布任何逆差都安全。判断需要同时考察借款用途、未来可贸易收入以及资本流动突然停止时的偿债安排。'] },
      { title: '有利息时，消费平滑怎样计算', paragraphs: ['把讲义例子的利率改为 5%，收入仍为第一期 60、第二期 100。若偏好满足 β(1+r)=1，且两期效用形式相同，最优条件要求两期消费相等。令两期消费都为 C，代入现值约束可得 C=(60×1.05+100)/2.05，约为 79.51。', '第一期需要借入约 19.51，第二期连本带息归还约 20.49，恰好等于第二期收入超过消费的部分。利息存在时，第二期还款额大于第一期借款额；如果漏掉利息，就会把资源约束算错。', '再设借款上限只有 10，原来的内部最优解便不可行。第一期消费最多为 70，第二期在偿还 10.5 后可消费 89.5。这个结果说明，不是所有观察到的消费波动都来自居民偏好变化，融资约束也会阻止平滑。', '若收入下降被判断为永久变化，两期收入都减少，消费平滑也无法恢复原来的消费水平。借贷可以改变资源在时间上的分配，却不能凭空创造可供偿付的未来资源。'] },
    ],
    sources: [
      { title: '原论文：Brookings Papers on Economic Activity，1981', url: 'https://www.brookings.edu/articles/the-current-account-and-macroeconomic-adjustment-in-the-1970s/', note: 'Jeffrey Sachs；原文含模型、石油冲击分析及讨论者意见。' },
      { title: '系统综述：The Intertemporal Approach to the Current Account', url: 'https://www.nber.org/papers/w4893', note: 'Obstfeld 与 Rogoff，1994 年工作论文，1995 年收入 Handbook of International Economics。', quote: 'The intertemporal approach views the current-account balance as the outcome of forward-looking dynamic saving and investment decisions.', translation: '跨期方法把经常账户余额看作前瞻性的动态储蓄与投资决策的结果。' },
    ],
    formulas: [{ expression: String.raw`C_1+\frac{C_2}{1+r}=Y_1+\frac{Y_2}{1+r}`, explanation: '无初始资产、无政府与投资的两期禀赋经济；两边分别为消费与收入的现值。' }, { expression: String.raw`u'(C_1)=\beta(1+r)u'(C_2)`, explanation: 'β 为主观折现因子。可自由借贷且为内部最优解时，边际效用满足欧拉条件。' }],
    figure: 'intertemporal-choice', related: ['sovereign-default', 'sudden-stop', 'international-intermediation'],
  },
  {
    id: 'sovereign-default', year: 1981, yearLabel: '1981',
    title: '主权债务与偿付意愿', authors: 'Jonathan Eaton · Mark Gersovitz',
    originalTitle: 'Debt with Potential Repudiation: Theoretical and Empirical Analysis', kind: 'theory',
    question: '缺少通常的破产清算程序，为什么国家仍会偿还对外债务？',
    lessonIds: ['sovereign-debt', 'development-finance', 'governance'], terms: ['主权违约', '偿付意愿', '有限承诺', '伊顿—格索维茨模型'],
    sections: [
      { title: '主权借款的特殊之处', paragraphs: ['对企业放贷，债权人通常可以依合同追索资产。面对主权国家，跨境执行和处置资产更加困难，债权人不能像接管普通企业那样接管国家。伊顿与格索维茨把这一约束放进借贷模型：偿债必须符合借款国自身的继续履约激励。', '问题因而包括两层。国家是否拥有足够资源，是偿付能力；即使拥有资源，它是否选择按约偿付，是偿付意愿。两者相关，但并不相同。'] },
      { title: '偿债与违约的比较', paragraphs: ['在收入有波动、国际借贷能够平滑消费的环境中，保留未来借款机会有价值。偿债会减少今天可用资源，却保留未来进入信贷市场的机会；违约免去部分当期偿付，却可能失去融资渠道并承担其他成本。', '政府在每一种收入与债务状态下比较两条路径的价值。当继续履约的价值高于违约价值时，承诺才可持续。债权人理解这种选择，因而不会无条件提供任意规模的贷款。'] },
      { title: '信用上限如何出现', paragraphs: ['随着债务上升，当前偿付负担增加，放弃未来融资的相对代价可能下降。债权人据此限制授信，形成内生的信用上限。在现代扩展模型中，债券价格还会反映下一期的违约概率与回收率。', '利差和可借款额度由借款国状态共同决定。收入下降既削弱偿付能力，也可能改变违约激励；债券价格下跌又提高新增借款成本，从而进一步收紧融资。'] },
      { title: '违约成本需要具体说明', paragraphs: ['原模型以失去未来借款机会作为重要惩罚机制。现实中还涉及贸易融资中断、金融机构损失、诉讼、国内支付困难和政治成本。分析时不能把“声誉受损”当成无需解释的万能原因。', '后续研究指出，如果违约国可以绕过制裁、在国际市场继续储蓄，仅依靠借贷排斥未必能支持大量债务。模型结论取决于违约后到底被限制了什么、限制能持续多久。'] },
      { title: '从债务比率到重组安排', paragraphs: ['债务占 GDP 比例描述负担，却不能单独识别违约风险。同样的比率，在本币长期债务与短期外币债务之间含义不同。稳定的税收、到期分布和外汇收入，会影响政府的选择空间。', '债务重组通过延期、降息或本金减记改变双方的继续履约收益。阅读重组方案时，应把现金流缓解和债务现值减轻分开，再考察方案是否恢复可持续的偿债激励。'] },
      { title: '借款价格怎样反映违约选择', paragraphs: ['用一个简化的一期债券例子说明后续模型的定价。债券到期承诺支付一单位，若违约则完全不回收；债权人风险中性，世界无风险利率为 5%。若下一期偿付概率为 90%，债券价格是 0.9/1.05，约为 0.857。政府每承诺偿付一单位，现在只能获得约 0.857 单位资源。', '这个价格并非由政府单方面决定。政府借款增加，下一期偿债负担就加重，债权人对偿付概率的判断也会变化。因此，“多发一些债券就一定获得同比例更多收入”并不成立；达到某种状态后，发行量增加可能伴随价格快速下跌。', '加入回收率后，违约状态下债权人仍可能取得部分支付，价格应把这项收入计入。若债权人厌恶风险，还要考虑违约是否集中发生在全球资金最紧张、损失边际价值最高的时候。只用平均违约率，可能无法解释市场利差。', '这一算例展示定价逻辑，并非原论文的数值估计。原模型以及后来引入随机收入、长期债务和重组的模型，都会因信息、违约成本和合同结构不同而得到不同的债务上限与价格函数。'] },
      { title: '配图观察：偿付能力', paragraphs: ['下方债务动态展示利率、经济增长与财政余额如何改变债务比率，帮助观察偿付能力。这项会计推演没有内生的违约选择；讨论伊顿—格索维茨的偿付意愿时，还要比较继续履约和违约的价值。'] },
    ],
    sources: [{ title: '原论文：The Review of Economic Studies，1981', url: 'https://academic.oup.com/restud/article-abstract/48/2/289/1572032', note: '期刊原始条目；全文访问取决于期刊或图书馆权限。' }],
    formulas: [{ expression: String.raw`V^{\mathrm{repay}}(b,y)\geq V^{\mathrm{default}}(y)`, explanation: 'b 为现有债务，y 为收入状态。只有继续偿付的价值不低于违约价值，债务承诺才满足激励约束。此式概括现代有限承诺模型的比较。' }],
    figure: 'debt-dynamics', related: ['intertemporal-account', 'original-sin', 'sudden-stop'],
  },
  {
    id: 'bank-runs', year: 1983, yearLabel: '1983',
    title: '银行挤兑与流动性保险', authors: 'Douglas Diamond · Philip Dybvig',
    originalTitle: 'Bank Runs, Deposit Insurance, and Liquidity', kind: 'theory',
    question: '长期资产本来能够偿付，银行为什么仍会遭遇挤兑？',
    lessonIds: ['crisis', 'governance', 'digital-money'], terms: ['银行挤兑', '流动性转换', '存款保险', '戴蒙德—迪布维格模型'],
    sections: [
      { title: '银行为什么提供随时可取的存款', paragraphs: ['居民不知道自己什么时候需要用钱。长期投资持有到期的收益较高，但提前清算会损失资源。如果每个人单独投资，就必须为偶然的早期消费需要保留低收益流动资产，或者在需要现金时折价变卖长期资产。', '银行把许多人的资金集合起来，预期只有一部分人提前取款，因而可以同时持有长期资产，并向居民提供较为稳定的早期支付。这种流动性保险具有经济价值。'] },
      { title: '三个时点与两种消费需要', paragraphs: ['在最初时点，居民存入资金；中间时点，一部分居民需要消费；最后时点，长期投资到期。早期消费需要属于个人信息，银行无法完全辨别谁真正急需资金，因此活期存款通常允许储户自行选择何时提款。', '只要等待的储户相信其他晚期消费者也会等待，银行就能按正常比例满足取款，保留足够长期资产。这是正常的均衡。它依靠存款合同和对他人行为的预期共同维持。'] },
      { title: '挤兑怎样自我实现', paragraphs: ['如果储户相信其他人都会提前提款，等待者可能最后拿不到钱。即使他原本不急需消费，也会选择抢先取款。银行为支付大量提款而清算长期资产，清算损失使原来的担忧成为事实。', '正常均衡和挤兑均衡可以出现在相同的资产基本面下。模型说明短期负债与长期资产的组合具有协调脆弱性；它没有声称现实中的所有挤兑都与资产质量无关。'] },
      { title: '保险、暂停支付与最后贷款人', paragraphs: ['可信的存款保险可以改变储户的预期：既然按承诺能够获得偿付，就不必仅因别人抢先提款而提前退出。保险的可信度依赖公共部门筹资能力、覆盖规则和执行制度。', '暂停支付可以阻止资产被过度清算，却可能阻碍真正需要资金的人消费。最后贷款人提供流动性，缓解临时现金缺口；如果资产已经严重亏损，还需要资本补充或处置安排。流动性支持与弥补资不抵债是不同任务。'] },
      { title: '从银行到影子银行', paragraphs: ['回购、货币市场基金和部分稳定币安排，也可能使用短期、可赎回的负债支持不完全流动的资产。投资者不再续作、要求更高抵押折扣或集中赎回，都会迫使发行方出售资产。', '类比必须检查合同细节：有无顺序支付、资产能否立即变现、是否承诺固定面值、谁承担损失。不能只因“可以赎回”就认定所有产品具有完全相同的挤兑机制。'] },
      { title: '用一份简化资产表检查挤兑', paragraphs: ['设银行收到 100 单位存款，保留 20 单位现金，把 80 单位投入长期项目。正常情况下，有 20 单位早期提款需要，现金足以支付；剩余储户等到项目到期。若项目每单位到期支付 1.2，晚期可分配资源为 96。此处的数字只用于说明清算机制。', '如果所有储户都要求立即取回本金，而长期资产提前出售每单位只能换回 0.7，银行最多立即取得 20+80×0.7=76。即使持有到期时总资源足以支付原有本金，集中提前提款也会造成现金支付不足。', '这个例子还区分两种问题。项目到期回报下跌，是资产质量恶化；资产没有恶化、但必须在不利时点清算，是流动性损失。现实危机中两者经常相互加强，单凭银行请求流动性支持，不能判断它最终是否有偿付能力。', '如果公共保险可信，储户可以不因担心落后于别人而抢先退出。若保险资金不足、覆盖范围不清，或者保险不覆盖该类负债，协调问题仍可能存在。因此，对合同与支持安排的判断必须具体到负债种类。'] },
      { title: '配图观察：短期融资的延伸', paragraphs: ['下方回购图属于影子银行的延伸例子，演示抵押折扣上升、补充担保与被迫出售之间的关系。戴蒙德—迪布维格原模型讨论储户流动性需要和提款协调；两者通过短期融资脆弱性相连，合同和触发机制各有区别。'] },
    ],
    sources: [{ title: '原论文：Journal of Political Economy，1983', url: 'https://www.journals.uchicago.edu/doi/10.1086/261155', note: '原论文讨论存款合同、均衡与保险安排。', quote: 'Traditional demand deposit contracts which provide liquidity have multiple equilibria, one of which is a bank run.', translation: '提供流动性的传统活期存款合同存在多个均衡，其中一个是银行挤兑。' }],
    figure: 'repo-liquidity', related: ['second-crisis', 'macroprudential', 'digital-currency'],
  },
  {
    id: 'exchange-disconnect', year: 1983, yearLabel: '1983',
    title: '汇率预测与随机游走', authors: 'Richard Meese · Kenneth Rogoff',
    originalTitle: 'Empirical Exchange Rate Models of the Seventies: Do They Fit Out of Sample?', kind: 'puzzle',
    question: '为什么复杂的汇率模型，常常难以胜过“下一期等于这一期”？',
    lessonIds: ['foundations', 'short-run', 'fx-market'], terms: ['汇率脱节之谜', '随机游走', '样本外预测', '米斯—罗格夫之谜'],
    sections: [
      { title: '解释过去与预测未来', paragraphs: ['模型可以在已经看到的数据上拟合得很好，却未必能预测新的观测。米斯与罗格夫比较了结构模型、时间序列模型和随机游走的样本外预测表现。随机游走基准将未来汇率的预测值设为当前汇率，没有使用额外的经济变量。', '这项研究检验的是预测能力。其结果后来成为“汇率脱节之谜”的重要起点，但预测困难与汇率完全不受基本面影响，并不是同一个命题。'] },
      { title: '原研究怎样设置比较', paragraphs: ['作者考察美元对英镑、德国马克、日元以及贸易加权美元汇率，比较一个月至十二个月的预测。结构模型包含弹性价格货币模型、黏性价格模型和纳入经常账户因素的模型。', '一项严格的安排是：部分结构模型甚至获得了解释变量未来的实际值。这使研究可以排除“只是没预测准未来货币供给或产出”这一解释。然而这些模型仍难以稳定击败随机游走。'] },
      { title: '为什么基本面模型也可能接近随机游走', paragraphs: ['汇率是一种资产价格，今天的价格包含对未来许多时期的判断。若新的公开信息到来难以预测，汇率变化也可能难以预测。对未来货币政策路径、风险补偿或长期均衡的小幅修正，都可能在今天引起较大价格变化。', '模型参数还可能随政策制度和市场结构变化。用过去估计的关系预测未来，会遭遇参数不稳定、数据修订、有限样本和变量测量误差。这些问题必须与理论本身的错误分别检查。'] },
      { title: '怎样做一次公平的检验', paragraphs: ['应当预先划分估计期和检验期，只使用预测当时可获得的信息，并保持预测期限一致。调整过很多模型以后才挑出表现最好的一个，容易把偶然拟合当成发现。评价还应比较预测误差及其统计不确定性。', '“预测方向正确”“平均误差较小”和“扣除成本后能交易获利”也是不同标准。某个模型在一段时期有效，不能推出它在其他币种、时期和交易条件下同样有效。'] },
      { title: '这项难题怎样改变研究方向', paragraphs: ['后续研究分别考察长期基本面、风险溢价、投资者信息差异、订单流和金融中介约束。课程中的短期模型仍有助于组织因果关系，但应用时需区分条件推演与无条件预测。', '例如，“在其他条件不变时，加息怎样影响资产需求”是一项比较静态分析；“下个月某货币一定升值”需要同时知道预期变化和所有其他冲击。前者成立，并不自动保证后者。'] },
    ],
    sources: [{ title: '原论文：Journal of International Economics，1983', url: 'https://www.sciencedirect.com/science/article/pii/002219968390017X', note: '原始预测比较与样本安排。', quote: 'The structural models perform poorly despite the fact that we base their forecasts on actual realized values of future explanatory variables.', translation: '尽管预测使用了解释变量未来的实际值，结构模型的表现仍然较差。' }, { title: '作者保存的论文入口', url: 'https://rogoff.scholars.harvard.edu/publications/empirical-exchange-rate-models-seventies-do-they-fit-out-sample', note: 'Kenneth Rogoff 的学术主页，列有论文附件。' }],
    related: ['forward-premium', 'microstructure', 'global-cycle'],
  },
  {
    id: 'forward-premium', year: 1984, yearLabel: '1984',
    title: '远期溢价之谜', authors: 'Eugene Fama',
    originalTitle: 'Forward and Spot Exchange Rates', kind: 'puzzle',
    question: '高利率货币为什么未必按利率平价所预测的幅度贬值？',
    lessonIds: ['short-run', 'enterprise', 'capital-markets'], terms: ['远期溢价之谜', '法马回归', '套息交易', '未抛补利率平价'],
    sections: [
      { title: '先固定汇率的标价方式', paragraphs: ['设 S 为一单位外币的本币价格，S 上升表示本币贬值。若本国利率高于外国利率，未抛补利率平价在风险中性等假设下要求本币预期贬值，以抵消利息优势。', '若抛补利率平价同时成立，远期升水近似等于本外币利差。于是可以用今天的远期升水，检验下一期的实际汇率变化是否符合这一预测。实际变化包含意外信息，因此需要在一组观测中作统计检验。'] },
      { title: '法马回归检验什么', paragraphs: ['将下一期对数即期汇率变化对当期远期升水作回归，在无偏预测的联合假设下，截距为零、斜率为一。许多经典样本却得到较小、甚至为负的斜率：高利率货币没有按理论要求贬值，有时还会升值。', '法马将远期价格中的预期汇率变化与溢价成分分开讨论。在维持理性预期的条件下，回归结果对风险溢价的波动及其与预期变化的协方差提出了严格要求。'] },
      { title: '远期升水不等于风险溢价', paragraphs: ['远期升水是远期价格与即期价格的差，可以直接观察。风险溢价是承担货币风险所需的预期补偿，通常不能直接观察。两个名称都含“溢价”，含义却不同。', '一笔远期合约锁定兑换价格；未对冲的外币存款则暴露于未来即期汇率风险。前者用于抛补套利比较，后者涉及对风险收益的估计。不能用未抛补平价的经验失败，直接否定抛补平价的无套利逻辑。'] },
      { title: '套息收益从哪里来', paragraphs: ['借入低利率货币、持有高利率货币，是套息交易的基本形式。如果高利率货币平均贬值不足以抵消利差，这种策略可能取得正的平均收益。但收益可能集中在平静时期，而在风险冲击中出现急剧亏损。', '风险补偿、罕见灾难、市场学习和预期偏差，都是相关解释。区分它们，需要调查预期、期权价格、极端时期收益及不同持有期限的证据；平均收益本身不能证明哪一种解释正确。'] },
      { title: '怎样联系企业的外汇管理', paragraphs: ['企业套期保值的目的通常是稳定未来现金流。远期报价包含利差形成的价格调整，它不会因为与今天即期价格不同就天然“划算”或“不划算”。应比较锁定后的本币收入、融资成本和未对冲时可承担的波动。', '课堂上的利率平价计算给出条件关系；市场报价和经验回归提醒我们，风险溢价、预期与预测误差需要单独处理。'] },
      { title: '配图观察：被检验的基准', paragraphs: ['下方未抛补利率平价图展示两种货币资产的预期收益如何比较，是理解回归原假设的基准。图中参数为教学设定；经验上的远期溢价之谜需要实际时间序列与样本外检验，不能由这张设定图直接证明或否定。'] },
    ],
    sources: [{ title: '原论文：Journal of Monetary Economics，1984', url: 'https://www.sciencedirect.com/science/article/abs/pii/0304393284900461', note: '原始法马回归与远期价格分解；正文采用固定标价方式说明。', quote: 'There is a general consensus that forward exchange rates have little if any power as forecasts of future spot exchange rates.', translation: '人们普遍认为，远期汇率对未来即期汇率的预测能力即使存在，也很有限。' }],
    formulas: [{ expression: String.raw`s_{t+1}-s_t=\alpha+\beta(f_t-s_t)+\varepsilon_{t+1}`, explanation: 's、f 分别为即期、远期汇率的对数，均按本币/外币标价。α=0、β=1 是特定联合假设下的限制。' }, { expression: String.raw`f_t-s_t=\mathbb{E}_t(s_{t+1}-s_t)+\pi_t`, explanation: '此处以远期升水减预期汇率变化定义 π。它是风险溢价的一种符号约定，不应与可直接观察的远期升水混同。' }],
    figure: 'uip', related: ['exchange-disconnect', 'funding-cip', 'microstructure'],
  },
  {
    id: 'lucas-paradox', year: 1990, yearLabel: '1990',
    title: '卢卡斯悖论', authors: 'Robert Lucas',
    originalTitle: "Why Doesn't Capital Flow from Rich to Poor Countries?", kind: 'puzzle',
    question: '资本稀缺的经济体，为什么没有吸引理论所预言的大规模资金流入？',
    lessonIds: ['globalization', 'development-finance'], terms: ['卢卡斯悖论', '资本边际产出', '人力资本', '配置之谜'],
    sections: [
      { title: '一项数量级上的疑问', paragraphs: ['新古典生产函数具有资本边际报酬递减的性质。如果两国技术相同、劳动可以直接比较，资本较少的国家应有较高的资本回报。开放资本市场后，资金应流向资本稀缺国，直到收益差缩小。', '卢卡斯在 1990 年用美国与印度作数量核算。讲义沿用的计算是：美国人均产出约为印度的 15 倍，资本份额取 0.4，简单模型就会推出印度资本边际产出约为美国的 58 倍。实际资本流动远没有与这一差距相称。'] },
      { title: '58 倍怎样算出来', paragraphs: ['在 y=Akᵅ 的生产函数中，人均产出差异全部归因于人均资本差异。消去 k 后，资本边际产出与人均产出的幂次相关。只要 α 小于一，贫国的人均产出越低，模型推算的资本回报就越高。', '这个结果对假设极其敏感。两国技术 A 相同、劳动同质、资本价格可比、没有税收和产权风险，都是推算所依赖的条件。58 倍是一项用来暴露模型前提的计算，不能当作当时投资印度可实际取得的回报率。'] },
      { title: '有效劳动与生产环境', paragraphs: ['受教育程度、技能、健康和组织能力会影响劳动与物质资本配合的效率。同样一台设备，在不同生产环境中创造的收益可能不同。卢卡斯讨论了人力资本差异及其外部性，说明修正劳动投入以后，原来推算的巨大差距会缩小。', '制度、基础设施和合同执行也影响投资者能够取得的收益。项目的社会产出、税前利润和外国投资者最终可汇出的风险调整收益，需要分开衡量。'] },
      { title: '借不到钱与没有高回报', paragraphs: ['一种解释认为，资本市场不完善阻碍高回报项目获得资金；另一种解释认为，看上去稀缺的物质资本实际上需要其他稀缺条件配合，真实回报没有那么高。两种解释对应的政策不同。', '前者要求改善融资与风险分担，后者还需要提高教育、生产组织和公共设施水平。把所有差异归为“资本不愿去穷国”，会遗漏投资机会本身的形成条件。'] },
      { title: '从总流入到净流入', paragraphs: ['观察资本流向时，要区分私人直接投资、债务融资、官方储备积累以及本国居民对外投资。一个国家可以吸引外商直接投资，同时因储蓄更高而净输出资本。', '因此，中国等高增长经济体的经常账户顺差，与外国企业在当地大量投资可以同时出现。卢卡斯悖论关注基础模型与资本配置之间的距离，全球失衡研究进一步讨论各类资产供求如何影响净流动方向。'] },
    ],
    sources: [{ title: '原论文：American Economic Review，1990', url: 'https://www.jstor.org/stable/2006549', note: 'American Economic Association 原刊归档，80(2)，92–96。原文短摘经大学保存的原刊扫描版核对。', quote: 'the marginal product of capital is higher in the less productive (i.e., in the poorer) economy.', translation: '资本的边际产出在生产率较低的经济体，也就是较贫穷的经济体中更高。' }, { title: '作者论文目录', url: 'https://voices.uchicago.edu/robertelucas/research/', note: '芝加哥大学 Robert Lucas 学术档案；核对原始书目信息。' }],
    formulas: [{ expression: String.raw`\frac{MPK_{\mathrm{poor}}}{MPK_{\mathrm{rich}}}=\left(\frac{y_{\mathrm{rich}}}{y_{\mathrm{poor}}}\right)^{(1-\alpha)/\alpha}`, explanation: '仅在相同技术、同质劳动与柯布—道格拉斯生产函数等假设下成立。α=0.4、产出比为 15 时，右侧约为 58。' }],
    related: ['feldstein-horioka', 'global-imbalances', 'home-bias'],
  },
  {
    id: 'home-bias', year: 1991, yearLabel: '1991',
    title: '国际资产组合的本国偏好', authors: 'Kenneth French · James Poterba',
    originalTitle: 'Investor Diversification and International Equity Markets', kind: 'puzzle',
    question: '跨国分散投资能够降低风险，投资者为什么仍集中持有本国资产？',
    lessonIds: ['globalization', 'capital-markets'], terms: ['本国偏好', '国际风险分散', '资产组合', '风险共担'],
    sections: [
      { title: '分散投资的基准', paragraphs: ['若各国资产收益并不完全同步，把一部分财富配置到海外，可以降低只受本国冲击的风险。在无交易成本、无信息差异等简化条件下，投资者通常不会把所有权益资产集中在本国市场。', 'French 与 Poterba 研究美国、日本和英国投资者的持股结构，发现本国权益资产所占比例远高于一个充分国际分散的基准。论文报告的是特定历史时期的持仓，不能把这些比例直接当作今天的市场事实。'] },
      { title: '怎样量化偏好', paragraphs: ['一种常用度量比较投资者实际持有的外国股票比例与全球股票市值基准中的外国市场比例。假如外国市场占全球可投资市值的 60%，投资者却只配置 12%，其国外持仓就明显低于该基准。', '基准的选择会影响测量。是否采用自由流通市值、是否排除不可投资股票、基金注册地是否等于底层资产所在地，都需要说明。不能仅凭券商账户开在国内，就判断全部风险暴露都在国内。'] },
      { title: '风险收益怎样影响配置', paragraphs: ['两类资产组合的风险取决于各自波动率、权重和相关系数。外国资产即使单独看波动很大，只要与本国资产的相关性足够低，仍可能降低组合风险。相关性越接近一，分散收益越有限。', '原研究也从持仓反推隐含的收益预期：要让非常集中的本国持仓符合简单最优配置，需要投资者明显看好本国相对收益。这提出了一个进一步的问题：这些预期来自信息优势，还是熟悉感和判断偏差？'] },
      { title: '商品、收入与金融风险', paragraphs: ['居民最终关心的是消费购买力。海外资产可能带来汇率风险，也可能对冲本国收入或进口价格风险。劳动收入、住房和企业经营已经构成本国风险暴露，只看股票账户会遗漏这些背景资产。', '交易税费、信息获取、法律执行和投资限制可以解释部分集中配置；非贸易品消费与货币风险也会影响最优权重。各种解释必须与实际持仓和收益数据对应。'] },
      { title: '金融开放是否实现了风险共担', paragraphs: ['持有外国资产增加，未必意味着危机中的消费得到同等保护。如果资产收益在压力时期同时下跌，或者外债到期迫使居民低价出售外国资产，平时计算出的分散收益会减少。', '课程中的风险共担图先使用清楚的状态与收益安排，展示跨国持股如何转移收入风险。再把相关性、汇率与负债加入，才能理解现实中的风险分散为什么比基准模型更困难。'] },
    ],
    sources: [{ title: '原论文：NBER 工作论文 3609', url: 'https://www.nber.org/papers/w3609', note: '1991 年发表于 American Economic Review。', quote: 'The benefits of international diversification have been recognized for decades.', translation: '国际分散投资的益处，几十年来一直为人所知。' }],
    formulas: [{ expression: String.raw`\sigma_p^2=w^2\sigma_h^2+(1-w)^2\sigma_f^2+2w(1-w)\rho\sigma_h\sigma_f`, explanation: 'w 为本国资产权重，σh、σf 为两类收益波动率，ρ 为相关系数。收益须先按同一货币口径计算。' }],
    figure: 'risk-sharing', related: ['feldstein-horioka', 'lucas-paradox', 'international-intermediation'],
  },
  {
    id: 'currency-networks', year: 1993, yearLabel: '1993',
    title: '国际货币的接受网络', authors: 'Kiminori Matsuyama · Nobuhiro Kiyotaki · Akihiko Matsui',
    originalTitle: 'Toward a Theory of International Currency', kind: 'theory',
    question: '没有统一指定世界货币，某一种货币为什么会被广泛接受？',
    lessonIds: ['foundations', 'dollar', 'renminbi', 'future'], terms: ['国际货币网络', '网络外部性', '货币接受', '路径依赖'],
    sections: [
      { title: '接受一种货币的理由', paragraphs: ['人们接受一张货币，通常因为相信下一位交易对手也会接受。货币的用途因此取决于其他人的选择。将这一点放入跨国交易，便能讨论一种货币如何超出发行国边界。', 'Matsuyama、Kiyotaki 与 Matsui 在两国随机匹配模型中，让居民在遇到交易对象时决定接受哪一种货币。货币的流通范围由交易机会和接受策略共同决定。'] },
      { title: '从交易匹配到接受范围', paragraphs: ['持有某种货币的收益，取决于遇到愿意收取它的卖家的概率，以及等待交易所耗费的时间。如果外国货币可以在更多交易中使用，持有它就更有吸引力；更多人持有又使商家更愿意接受。', '两国规模与经济联系改变这种收益。较大的市场提供更多交易机会，更密切的跨国联系提高使用国际货币的便利。但这些因素并不总能唯一确定最后采用哪一种货币。'] },
      { title: '为什么可能有多个均衡', paragraphs: ['模型可以出现各国只在国内使用本币、一种货币跨国流通、两种货币均被国际接受等均衡。某种安排一旦普遍存在，个体继续沿用它可能是合理选择。', '这说明既有使用习惯能够持续，却不意味着中心货币永远不能更换。交易联系、接受成本与初始使用范围变化，都可能使原来的均衡失去稳定性。实际更替速度需要额外的制度和历史证据。'] },
      { title: '网络便利也有资源成本', paragraphs: ['国际使用扩大可提高发行国居民的交易便利，但货币供给与持有成本同样重要。在总量固定的设定中，外国持有增加也可能挤压国内可用货币。原论文因而讨论货币流通范围变化的福利条件。', '现实中的支付网络、做市商、抵押品与债券市场远比基准模型复杂。该模型首先解释接受意愿如何相互依赖；它没有直接给出某种货币应占多少储备或多少贸易结算份额。'] },
      { title: '与美元和人民币的联系', paragraphs: ['交易计价、贸易融资、外汇对冲、清算和储备持有之间存在互补关系。企业使用一种货币开票，可能更愿意以同币种融资；市场交易增多，又可能降低对冲成本。', '但货币的不同职能可以分开变化。支付份额上升不等于储备地位立即提高；大型经济的存在也不自动形成深厚、开放且可信的金融市场。分析国际化时，应分别观察各项职能及其相互支持的条件。'] },
    ],
    sources: [{ title: '原论文：The Review of Economic Studies，1993', url: 'https://academic.oup.com/restud/article-abstract/60/2/283/1574328', note: '原始随机匹配模型；发表于 60(2)，283–307。', quote: 'There are multiple equilibria, which differ in the areas of circulation of the two currencies.', translation: '存在多个均衡，两种货币的流通范围在这些均衡中有所不同。' }],
    figure: 'dollar-network', related: ['dominant-currency', 'digital-currency', 'safe-assets'],
  },
  {
    id: 'second-crisis', year: 1994, yearLabel: '1994',
    title: '第二代货币危机：政策选择与预期', authors: 'Maurice Obstfeld',
    originalTitle: 'The Logic of Currency Crises', kind: 'theory',
    question: '外汇储备尚未耗尽，政府为什么可能主动放弃固定汇率？',
    lessonIds: ['currency-crises', 'regimes', 'policy'], terms: ['第二代货币危机', '自我实现预期', '多重均衡', '保卫汇率'],
    sections: [
      { title: '欧洲汇率机制提出的问题', paragraphs: ['1992—1993 年欧洲汇率机制危机中，一些政府拥有相当的融资能力，却仍选择让货币退出原有平价。仅用财政赤字推动货币扩张、储备被逐渐消耗的故事，难以完整解释这些事件。', '奥布斯特费尔德让政府在保卫汇率和放弃平价之间进行选择。维持承诺可能保护信誉，也可能要求高利率和紧缩；放弃承诺可以缓解部分国内压力，却承担贬值及信誉成本。'] },
      { title: '投机预期怎样改变政策成本', paragraphs: ['市场若预期贬值，持有本币资产就需要更高利率补偿。高利率会增加债务负担、压低投资，可能加重失业和银行压力。政府原本愿意承担的固定汇率承诺，因此变得更昂贵。', '如果这些成本超过政府重视的信誉和稳定收益，放弃平价就成为最优反应。市场的预期通过政策成本影响政府选择，政府选择又验证了原来的预期。'] },
      { title: '脆弱区间与多重均衡', paragraphs: ['基本面非常稳健时，即使出现攻击，政府也愿意守住平价；基本面非常差时，即使没有额外恐慌，原平价也难以维持。两者之间可能存在一个区间：不受攻击时可以维持，受到攻击后则选择放弃。', '多重均衡出现在这个中间区间。基本面仍然决定经济是否处于脆弱范围，预期决定其中哪一种结果实现。因此，自我实现危机并不等于任何国家都能被任意攻击击倒。'] },
      { title: '储备充足为何仍不够', paragraphs: ['外汇储备和国际借款能增加防守资源，却不能取消利率提高对就业、财政和金融机构的影响。政府能否守住，以及是否愿意一直守住，需要分别判断。', '救助安排若可信并能降低临时防守成本，可以协调预期；如果承诺本身缺乏财政与政治支持，仅宣布继续守住平价，可能无法改变市场判断。'] },
      { title: '与其他危机模型的分工', paragraphs: ['第一代模型强调既定政策与固定汇率不相容，第二代强调政府反应与市场预期的相互作用。第三代模型进一步加入外币负债、资产价格和金融机构的脆弱性。不同危机中，几种机制可能同时出现。', '模型可以解释一种危机为何可能发生，却不自动给出精确发生日期。寻找触发因素时，需要结合工资合同、债务到期、选举、政策声明与跨境资金流动等具体信息。'] },
    ],
    sources: [{ title: '原论文：The Logic of Currency Crises', url: 'https://www.nber.org/papers/w4640', note: '1994 年工作论文与同年正式发表版本。', quote: 'In a setting of purposeful action by the authorities, the possibility of self-fulfilling crises becomes important.', translation: '当政策当局作出有目的的选择时，自我实现危机的可能性就变得重要。' }],
    related: ['bank-runs', 'third-crisis', 'fear-floating'],
  },
  {
    id: 'new-open-macro', year: 1994, yearLabel: '1994 工作论文 · 1995 期刊',
    title: '新开放经济宏观经济学', authors: 'Maurice Obstfeld · Kenneth Rogoff',
    originalTitle: 'Exchange Rate Dynamics Redux', kind: 'theory',
    question: '怎样在同一模型中讨论价格黏性、跨期选择和政策的福利影响？',
    lessonIds: ['policy', 'short-run', 'accounts'], terms: ['新开放经济宏观经济学', 'Redux 模型', '垄断竞争', '国际政策溢出'],
    sections: [
      { title: '把短期与跨期分析连接起来', paragraphs: ['传统开放经济模型擅长说明短期需求传导，但常用预设的消费、投资和货币需求关系。跨期模型明确描述家庭选择，却在早期版本中通常采用价格灵活的设定。Redux 模型将跨期优化与短期价格黏性放在同一框架内。', '论文在 1994 年发布工作论文，1995 年发表于《政治经济学杂志》。研究对象是相互联系的两国经济，因而可以同时考察本国政策和外国居民受到的影响。'] },
      { title: '家庭、企业和市场', paragraphs: ['居民选择消费、劳动和货币持有，也通过国际债券转移不同时期的资源。企业生产差异化产品，具有一定定价能力。价格在短期内不能立即调整，货币冲击因此能够改变实际需求与产出。', '垄断竞争使产出低于一个没有加价扭曲的基准；价格黏性又使需求变化暂时影响生产。这两项假设共同决定政策的福利后果。只保留“贬值促进出口”一句话，会遗漏模型的重要结构。'] },
      { title: '货币冲击怎样跨境传递', paragraphs: ['本国货币扩张改变利率、汇率、相对需求和家庭财富。短期内，预先设定的价格使购买力与产品需求发生变化；经常账户的盈亏改变对外债权债务，影响价格调整后的长期消费。', '因而，短期冲击可以通过财富积累留下长期影响。模型需要同时解出汇率和经常账户，不能把每一期都看作相互独立的静态均衡。'] },
      { title: '产出增加是否意味着福利改善', paragraphs: ['福利取决于消费收益、劳动付出以及商品之间的替代关系。某项政策增加出口，可能同时改变贸易条件和劳动负担；外国居民也可能从更丰富或更便宜的商品中受益。', '因此，“竞争性贬值必定损人利己”或“货币扩张必定让双方受益”都不是无条件结论。必须说明定价货币、价格调整、市场加价和财政安排。Redux 的意义在于可以把这些判断写成可比较的福利计算。'] },
      { title: '后续研究改变了哪些假设', paragraphs: ['生产者货币定价、本币定价和主导货币定价，会给出不同的汇率传递路径。市场不完备、家庭异质性、金融中介和进口中间品进一步改变政策效果。', '阅读课程中的 IS–LM–FX 图时，可以先用它掌握方向，再用这一研究传统追问微观前提：谁调整消费，谁承担汇率风险，价格何时重设，国际资产变化又由谁持有。'] },
    ],
    sources: [{ title: '原论文：Journal of Political Economy，1995', url: 'https://www.journals.uchicago.edu/doi/10.1086/261997', note: '两国、垄断竞争与黏性价格的原始框架。', quote: 'Our analysis leads to a novel perspective on the international welfare spillovers due to monetary and fiscal policies.', translation: '我们的分析为货币和财政政策的国际福利溢出提供了新的观察角度。' }, { title: '首发工作论文，1994', url: 'https://www.nber.org/papers/w4693', note: 'April 1994，NBER Working Paper 4693。' }],
    related: ['intertemporal-account', 'dominant-currency', 'global-cycle', 'mundell-fleming'],
  },
  {
    id: 'sudden-stop', year: 1998, yearLabel: '1998',
    title: '资本流动的突然停止', authors: 'Guillermo Calvo',
    originalTitle: 'Capital Flows and Capital-Market Crises: The Simple Economics of Sudden Stops', kind: 'theory',
    question: '外部融资突然中断，怎样从国际收支传导到企业破产与产出下降？',
    lessonIds: ['globalization', 'currency-crises', 'crisis'], terms: ['突然停止', '资本流动逆转', '外部融资', '非贸易品价格'],
    sections: [
      { title: '先看融资缺口', paragraphs: ['经常账户逆差需要相应的外部融资或储备使用。当愿意提供资金的投资者突然退出，原来的支出安排就难以继续。Calvo 把这种外部信用供给的急剧收缩称为突然停止，并分析其对实体经济的影响。', '这类冲击可以来自国际投资者风险偏好、共同债权人的资产负债表，也可以来自本国情况变化。研究机制时，要区分外部融资停止的原因与停止之后的放大过程。'] },
      { title: '支出必须怎样调整', paragraphs: ['如果储备和替代融资不足，经济必须减少对外国资源的净吸收。进口压缩、出口增加和国内需求下降共同推动经常账户调整；短期内数量不易变化时，调整可能更多落在产出和就业上。', '国内支出收缩会压低非贸易品需求，其相对价格下降，实际汇率发生调整。那些收入来自国内、负债却以外币或可贸易品计值的部门，资产负债表尤其脆弱。'] },
      { title: '从相对价格到破产', paragraphs: ['非贸易品价格和企业收入下降，会降低抵押品价值和净资产。若融资额度与净资产相连，企业便进一步削减投资和雇佣，资产出售又可能继续压低价格。最初的融资冲击因此被放大。', '讲义中的外币债务案例展示同一方向的作用：本币贬值抬高外币债务的本币价值，而本币收入不能同步增加，偿债负担就会加重。'] },
      { title: '净资本流动不能说明全部风险', paragraphs: ['即使经常账户逆差不大，银行和企业也可能有大量短期外债需要滚动融资。若只看净流入，会遗漏外国投资者撤出和本国居民资金外移的分别变化。', 'Calvo 的原文还强调，不能因逆差被外国直接投资所覆盖，就宣布经济不存在突然停止风险。资金可以在国内体系中重新分配，期限、清偿承诺和部门暴露仍然重要。股权式风险分担与短期债务的作用也不相同。'] },
      { title: '缓冲措施及其边界', paragraphs: ['储备、稳定的长期融资、外币收入对冲和流动性安排可以延缓被迫调整。宏观审慎政策则尝试在繁荣期减少容易放大的融资结构。', '原论文没有提供一套能够精确预测每次危机日期的模型。识别脆弱性与判断触发时点应当分开；政策还必须权衡持有缓冲的成本，以及长期限制融资可能损失的投资机会。'] },
    ],
    sources: [{ title: '原论文：马里兰大学研究档案', url: 'https://drum.lib.umd.edu/items/d4c197f5-130f-4c68-9814-c0f14aac82a6', note: 'Journal of Applied Economics，1998，1(1)，35–54。', quote: 'However, equity and long-term bond financing may shield the economy from sudden stop crises.', translation: '不过，股权融资和长期债券融资可能保护经济，使其免受突然停止危机的冲击。' }],
    figure: 'currency-mismatch', related: ['third-crisis', 'original-sin', 'macroprudential'],
  },
  {
    id: 'original-sin', year: 1999, yearLabel: '1999',
    title: '债务币种与“原罪”', authors: 'Barry Eichengreen · Ricardo Hausmann',
    originalTitle: 'Exchange Rates and Financial Fragility', kind: 'theory',
    question: '为什么一些经济体难以用本币对外借款，这会带来什么约束？',
    lessonIds: ['sovereign-debt', 'currency-crises', 'renminbi', 'development-finance'], terms: ['原罪', '货币错配', '外币债务', '本币融资'],
    sections: [
      { title: '融资币种为何不是自由选择', paragraphs: ['新兴经济体企业可能拥有本币收入，却只能以美元等外币获得较长期的融资。Eichengreen 与 Hausmann 将本币难以用于对外借款、或难以用于国内长期借款的市场不完备，称为“原罪”。后续研究常将重点放在国际借款的币种约束。', '这个名称描述融资条件，不是对借款国的道德评价。是否能够用本币借款，受到市场规模、信用制度、投资者接受度和国际资产组合选择等因素影响。'] },
      { title: '债务如何随汇率变化', paragraphs: ['设企业资产和收入以本币为主，负债中有美元债务。若本币贬值，美元债务折成本币的金额增加，但本币收入未必同步增加，企业净资产因而下降。对出口商而言，美元收入可以抵消一部分影响；对面向国内的企业，抵消可能很小。', '判断货币错配要把资产、负债、经营现金流与衍生品头寸合并观察。仅知道企业借了美元，尚不足以说明它承担了多少净汇率风险。'] },
      { title: '固定汇率与浮动汇率的两难', paragraphs: ['固定汇率暂时降低汇率波动，可能使借款者忽视对冲需要；但承诺一旦失守，错配损失会集中暴露。浮动汇率可以吸收部分外部冲击，却也可能立即放大现有外币负债。', '因此，改变汇率制度并不能自动消除已经存在的债务结构。融资币种与期限影响制度选择，制度承诺又可能反过来影响融资行为。两者是相互作用的。'] },
      { title: '“原罪”与货币错配并不相同', paragraphs: ['不能在国际市场发行本币债，是一种融资约束；资产负债表实际存在净外币敞口，是一种风险暴露。通过持有外汇资产、取得外币经营收入或对冲，借款者可以在一定程度上缓解后者。', '反过来，即使本币债券市场已经发展，海外投资者也可能借入外币购买本币债券，或在风险变化时集中退出。币种风险改变了承担者，并不意味着跨境融资从此没有流动性与价格风险。'] },
      { title: '本币市场建设怎样发挥作用', paragraphs: ['稳定的宏观环境、可信的合同执行、持续的本币收益率曲线和较广的投资者基础，有助于扩大本币长期融资。单靠宣布某种货币可以使用，并不能形成足够的市场深度。', '比较国家经验时，应同时看对外债务币种、本币债券持有人、外汇衍生品可得性和市场流动性。国际化可以增加本币融资选择，但还需管理外资集中持有和跨境退出带来的波动。'] },
    ],
    sources: [{ title: '原论文：Exchange Rates and Financial Fragility', url: 'https://www.nber.org/papers/w7418', note: '1999 年 Jackson Hole 论文，同年 NBER 工作论文 7418；以下短摘说明“原罪”假说中的市场约束。', quote: 'an incompleteness in financial markets which prevents the domestic currency from being used to borrow abroad', translation: '一种金融市场的不完备，使本国货币无法被用于对外借款。' }],
    formulas: [{ expression: String.raw`N=A_{\mathrm{LC}}+S A_{\mathrm{FX}}-D_{\mathrm{LC}}-S D_{\mathrm{FX}}`, explanation: 'N 为本币净资产，S 为本币/外币汇率。其他项目暂不变时，净外币负债越大，本币贬值对净资产的打击越大。' }],
    figure: 'currency-mismatch', related: ['third-crisis', 'fear-floating', 'currency-networks'],
  },
  {
    id: 'third-crisis', year: 1999, yearLabel: '1999',
    title: '第三代货币危机：资产负债表', authors: 'Paul Krugman 等',
    originalTitle: 'Balance Sheets, the Transfer Problem, and Financial Crises', kind: 'theory',
    question: '为什么贬值本应改善出口，却可能伴随投资与产出的崩塌？',
    lessonIds: ['currency-crises', 'crisis', 'enterprise'], terms: ['第三代货币危机', '资产负债表效应', '金融加速器', '贬值的紧缩效应'],
    sections: [
      { title: '亚洲金融危机后的解释', paragraphs: ['1997—1998 年的危机使研究者更加关注企业和银行的资产负债结构。一些经济体并没有典型的巨额财政赤字，却在资本流动逆转后同时经历货币贬值、信贷收缩与投资下降。', '“第三代模型”是一组研究的统称，包含银行挤兑、道德风险和资产负债表等机制。本条以 Krugman 1999 年的论文为主，讨论外币债务、净资产与投资相互作用的路径。'] },
      { title: '企业为什么依赖净资产', paragraphs: ['当债权人无法完全监督项目和偿债行为时，愿意提供的融资可能与企业自身净资产相联系。净资产越高，能够承受的损失和可提供的抵押越多，融资约束越宽松。', '设企业主要拥有国内资产，却承担外币债务。本币贬值抬高债务本币价值，使净资产下降。即使企业仍拥有生产能力，也可能因为无法筹集流动资金和投资资金而缩减经营。'] },
      { title: '贬值的两个方向', paragraphs: ['商品市场中，实际贬值可能改善本国产品的相对竞争力，刺激净出口。资产负债表中，贬值可能加重外币债务，压低国内投资与需求。总效果取决于两条通道的相对大小。', '进口投入较多、出口短期内难以扩张、外币债务敞口较大时，竞争力改善可能来得较慢，财务损失却立即出现。因此，不能仅凭贬值方向判断产出一定增加。'] },
      { title: '资本流动与净资产的反馈', paragraphs: ['融资减少要求经济向国外转移更多可贸易资源，实际汇率随之调整；汇率调整又恶化企业资产负债表，进一步压低投资。投资下降削弱外国投资者愿意继续提供资金的基础，形成反馈。', '在某些模型条件下，乐观预期支持高投资和较强净资产，悲观预期则支持资本退出与低投资，因而出现多重均衡。是否存在这种区间，取决于债务币种、融资约束及相对价格的反应。'] },
      { title: '从机制到政策比较', paragraphs: ['提高利率可能减轻贬值压力，却增加国内融资成本；允许贬值可以缓解外部平衡，又可能打击外币借款者。分析政策时，需要同时记录两种成本，不能只观察汇率是否稳定。', '减少未对冲外币债务、延长期限、提高资本缓冲，以及在危机中修复资产负债表，分别针对不同环节。模型帮助确定传导渠道，政策选择仍需要知道负债究竟集中在哪些企业和金融机构。'] },
    ],
    sources: [{ title: '原论文：作者保存的期刊全文', url: 'https://www.princeton.edu/~pkrugman/krugmanbalance.pdf', note: 'International Tax and Public Finance，1999，6，459–472。以下为摘要中列出的一个机制。', quote: 'the role of companies’ balance sheets in determining their ability to invest', translation: '企业资产负债表在决定其投资能力方面的作用。' }],
    figure: 'currency-mismatch', related: ['original-sin', 'sudden-stop', 'second-crisis', 'macroprudential'],
  },
  {
    id: 'microstructure', year: 1999, yearLabel: '1999 工作论文 · 2002 期刊',
    title: '订单流与汇率微观结构', authors: 'Martin Evans · Richard Lyons',
    originalTitle: 'Order Flow and Exchange Rate Dynamics', kind: 'theory',
    question: '分散在企业、投资者和交易商手中的信息，怎样进入汇率？',
    lessonIds: ['fx-market', 'short-run', 'enterprise'], terms: ['订单流', '市场微观结构', '交易商', '价格发现'],
    sections: [
      { title: '宏观新闻以外的信息', paragraphs: ['利率、货币供给和产出是重要信息，但外汇交易还来自企业收付款、基金调仓和投资者对未来的不同判断。这些需求未必在同一时刻成为所有人的公共信息。', 'Evans 与 Lyons 将订单流引入汇率模型，研究客户需求如何通过交易商之间的交易被汇总，并进入价格。工作论文发表于 1999 年，期刊版本发表于 2002 年。'] },
      { title: '订单流不是成交量', paragraphs: ['每一笔买入都有对应的卖出，所以把买卖双方金额相减不会得到有意义的需求指标。微观结构中的订单流按交易发起方向赋予符号：主动买入一方发起的交易记为正，主动卖出记为负。', '成交量只表示交易规模，订单流则包含买卖压力的方向。两天成交额相同，若一天主动买入美元更多、另一天主动卖出更多，价格传递的信息可能不同。'] },
      { title: '交易商怎样调整报价', paragraphs: ['客户订单使交易商持仓改变。交易商可以在银行间市场转移风险；当整个市场都要吸收同一方向的净头寸时，价格需要调整，使最终持有人愿意承担这些风险。', '订单还可能透露尚未公开的基本面信息。例如企业汇款、投资组合调整和分散的经营观察，通过交易被市场逐渐识别。价格变化因此既可能反映信息，也可能反映有限风险承受能力下的头寸调整。'] },
      { title: '原研究的证据应怎样理解', paragraphs: ['作者在特定时期的交易商数据中发现，订单流对每日汇率变化具有较强解释力，也改善了部分短期预测。这个结果推动了将微观交易过程与宏观汇率理论结合的研究。', '同时期相关关系不自动等于可交易的领先信号。订单可能响应汇率变化，研究者得到的订单数据也未必是市场参与者当时可见的信息。评估预测时必须检查信息时点、样本和交易成本。'] },
      { title: '电子交易时代的延伸', paragraphs: ['交易平台和算法改变了订单的产生、拆分和执行方式；同一个投资决策可能被分成很多小单。流动性在不同平台间分散，交易商库存和客户分类也会影响订单流的含义。', '对课程而言，这一视角补上了“宏观信息如何形成报价”的过程。它与资产定价和利率平价可以结合：前者描述风险与均衡回报，微观结构则解释信息和交易如何推动市场靠近新的价格。'] },
    ],
    sources: [{ title: '原论文：Journal of Political Economy，2002', url: 'https://www.journals.uchicago.edu/doi/10.1086/324391', note: '正式发表版本；工作论文为 NBER 7317（1999）。' }, { title: '首发工作论文', url: 'https://www.nber.org/papers/w7317', note: '1999 年模型及原始交易数据分析。', quote: 'Order flow is the proximate determinant of price in all microstructure models.', translation: '在各类微观结构模型中，订单流都是价格的直接决定因素。' }],
    formulas: [{ expression: String.raw`\Delta s_t=\beta_r\Delta r_t+\beta_x x_t+\varepsilon_t`, explanation: '微观结构经验方程的简化写法：Δr 表示宏观利率信息，x 为有方向的订单流。系数和变量定义须与实际数据口径相配。' }],
    related: ['exchange-disconnect', 'forward-premium', 'funding-cip'],
  },
  {
    id: 'fear-floating', year: 2000, yearLabel: '2000 工作论文 · 2002 期刊',
    title: '浮动恐惧', authors: 'Guillermo Calvo · Carmen Reinhart',
    originalTitle: 'Fear of Floating', kind: 'puzzle',
    question: '一些宣布浮动汇率的经济体，为什么仍频繁干预汇率？',
    lessonIds: ['regimes', 'policy', 'currency-crises'], terms: ['浮动恐惧', '事实汇率制度', '汇率传递', '有管理浮动'],
    sections: [
      { title: '制度名称与实际操作', paragraphs: ['一个国家可以在官方分类中采用浮动汇率，同时通过利率、外汇储备和其他措施减少汇率变化。Calvo 与 Reinhart 比较汇率、储备、利率和货币变量的波动，指出制度标签并不总能准确描述实际政策。', '论文所说的“恐惧”是对一类系统性政策行为的概括。它需要用数据检验，不能仅凭一次外汇干预，就认定一个国家实际上实行固定汇率。'] },
      { title: '为什么不愿让汇率充分调整', paragraphs: ['若进口价格对国内通胀传递较快，贬值可能影响物价稳定与政策信誉。若企业和银行存在大量未对冲外币债务，贬值又会损害净资产。这些成本会促使当局平滑汇率波动。', '融资市场还可能把急剧贬值视为信用风险上升，要求更高利率或减少授信。政策当局因此同时面对国内需求、物价和金融稳定之间的权衡。'] },
      { title: '应当观察哪些变量', paragraphs: ['判断事实制度，要把汇率波动与储备和利率变化放在一起。汇率很稳定，可能因为经济受到的冲击很小，也可能因为央行付出很大干预成本。单独观察稳定的汇率路径无法区分二者。', '储备变化还包含估值、利息和政府交易；利率调整也可能服务于国内通胀目标。经验分类需要扣除这些因素，并说明比较的样本、频率与基准国家。'] },
      { title: '浮动仍然可能提供缓冲', paragraphs: ['浮动恐惧不意味着汇率弹性完全没有价值。适度调整可以吸收贸易和资本流动冲击，减少把所有压力转移到利率和产出上的需要。制度选择可以位于严格固定与自由浮动之间。', '关键在于现有债务结构和政策可信度。先减少货币错配、建立更稳定的本币金融市场，可能扩大未来允许汇率浮动的空间。'] },
      { title: '如何比较不同国家的制度', paragraphs: ['同样称为有管理浮动，操作目标可能不同：有的重点防止市场失序，有的维持某个水平，有的关注一篮子货币。比较时需要查央行目标、实际干预和资本流动条件。', '这一研究也提醒我们，三元悖论的经验检验不能只依赖官方标签。真正影响利率独立性的，是实际汇率承诺与资本流动程度，以及当局在压力下愿意承担的成本。'] },
    ],
    sources: [{ title: '原论文：Fear of Floating', url: 'https://www.nber.org/papers/w7993', note: '2000 年工作论文，2002 年发表于 Quarterly Journal of Economics；短摘概括作者在当时样本中的判断。', quote: 'the fear of floating is pervasive, even among some of the developed countries.', translation: '浮动恐惧相当普遍，甚至在部分发达国家中也是如此。' }],
    related: ['original-sin', 'second-crisis', 'global-cycle', 'mundell-fleming'],
  },
  {
    id: 'international-intermediation', year: 2005, yearLabel: '2005 工作论文 · 2007 发表',
    title: '国际金融中介与估值调整', authors: 'Pierre-Olivier Gourinchas · Hélène Rey',
    originalTitle: 'From World Banker to World Venture Capitalist: US External Adjustment and the Exorbitant Privilege', kind: 'theory',
    question: '对外资产和负债的结构，怎样改变经常账户与国际财富的关系？',
    lessonIds: ['accounts', 'dollar', 'capital-markets', 'future'], terms: ['估值效应', '国际金融中介', '过度特权', '净对外资产'],
    sections: [
      { title: '经常账户之外的财富变化', paragraphs: ['一国净对外资产不会只随经常账户累积变化。股票和债券价格变化、汇率变化以及统计调整，都能改变既有资产与负债的市值。当跨境总头寸很大时，即使回报率变化很小，估值变动也可能相当可观。', 'Gourinchas 与 Rey 重新构建美国对外资产负债数据，考察资产结构和回报差异，并把贸易调整与金融估值调整放进统一的外部约束中。'] },
      { title: '为什么总头寸很重要', paragraphs: ['设一国对外资产为 100、负债为 110，净负债为 10。如果只观察净值，看不出它同时承担了很大的双向资产价格风险。若资产回报高于负债回报，即使净负债存在，也可能获得正的投资收益。', '回报差可以来自资产类别构成，也可以来自同类资产的收益差别。前者例如持有较多股票与直接投资、发行较多债务；后者可能涉及流动性、风险、税制和测量。两者应分开计算。'] },
      { title: '汇率变化的估值通道', paragraphs: ['若资产较多以外币计值、负债较多以本币计值，本币贬值会提高外币资产折算后的本币价值，而本币负债金额不变。在其他条件相同时，净对外资产因而改善。', '反过来，若本国大量承担外币负债，贬值可能恶化净资产。相同汇率变化对不同国家和部门的效果相反，取决于实际币种暴露，而非简单取决于它是债权国还是债务国。'] },
      { title: '高平均回报与危机损失', paragraphs: ['持有风险资产、提供较安全负债的中介，平时可能获得较高平均收益，但在全球风险冲击中也可能承担较大损失。把风险溢价当成无条件、无风险的融资特权，会误读资产组合的性质。', '“过度特权”的实证大小还受到资本利得测量、直接投资估值和收益口径影响。现金投资收益与包含资本利得的总回报不是同一个数，比较研究需要先统一口径。'] },
      { title: '外部调整怎样完成', paragraphs: ['对外头寸恶化后，未来可以通过贸易余额改善，也可以通过资产负债回报差实现部分调整。两种通道都受跨期约束；估值收益不能被假定为每年稳定到来的补贴。', '课程中的国际投资头寸图可以将交易流量、汇率估值和资产价格估值分别打开。这样才能看清：某一年净对外资产改善，究竟来自更多储蓄，还是既有头寸的市值变化。'] },
    ],
    sources: [{ title: '原论文：NBER 工作论文 11563', url: 'https://www.nber.org/papers/w11563', note: '2005 年工作论文，2007 年收入 G7 Current Account Imbalances: Sustainability and Adjustment。' }, { title: '相关原论文：International Financial Adjustment', url: 'https://www.nber.org/papers/w11155', note: '2005 年工作论文，2007 年发表于 Journal of Political Economy。', quote: 'The exchange rate affects the trade balance and the valuation of net foreign assets.', translation: '汇率影响贸易余额，也影响净对外资产的估值。' }],
    formulas: [{ expression: String.raw`NFA_t-NFA_{t-1}=CA_t+KA_t+VAL_t+O_t`, explanation: '在一致统计口径下，净对外资产变化可分为经常账户、资本账户、估值变动和其他调整；统计差异需另行核对。' }],
    figure: 'iip-valuation', related: ['intertemporal-account', 'global-imbalances', 'safe-assets', 'original-sin'],
  },
  {
    id: 'global-imbalances', year: 2006, yearLabel: '2006 工作论文 · 2008 期刊',
    title: '全球失衡与金融资产供给', authors: 'Ricardo Caballero · Emmanuel Farhi · Pierre-Olivier Gourinchas',
    originalTitle: 'An Equilibrium Model of “Global Imbalances” and Low Interest Rates', kind: 'theory',
    question: '为什么一些快速增长的经济体输出储蓄，而美国持续吸收资金？',
    lessonIds: ['accounts', 'globalization', 'dollar', 'crisis'], terms: ['全球失衡', '金融资产供给', '储蓄过剩', '低利率'],
    sections: [
      { title: '需要同时解释的现象', paragraphs: ['在全球金融危机之前，美国经常账户逆差扩大，长期实际利率下降，美国资产在国际组合中的地位上升。简单的资本稀缺逻辑难以同时解释这些现象：快速增长、资本相对稀缺的经济体，本应更容易成为净借款者。', 'Caballero、Farhi 与 Gourinchas 从金融资产供给差异出发。一个经济体能够生产很多商品，并不意味着它同样能够发行大量可信、可交易的资产。'] },
      { title: '未来收入能有多少变成可交易资产', paragraphs: ['模型区分实际生产能力与把未来收入承诺给投资者的能力。合同执行、企业治理和金融制度较弱时，即使未来产出很大，能用于支持可交易金融资产的部分也可能有限。', '居民需要持有资产来养老、应付不确定性和转移财富。如果国内合意资产供给不足，储蓄就可能购买外国资产。这使增长较快的地区在投资增加的同时仍可能净输出储蓄。'] },
      { title: '利率与资产价格怎样调整', paragraphs: ['资产需求增加而供给不能同步扩大，会推高资产价格并降低均衡回报。能够较稳定地发行资产的经济体吸收外国资金，对应经常账户逆差及国际资产组合变化。', '这是一种全球均衡解释：顺差国和逆差国的行为需要共同分析。仅将美国逆差归为美国居民消费选择，或仅将其归为国外储蓄，都可能遗漏另一侧如何调整。'] },
      { title: '与安全资产短缺的区别', paragraphs: ['这篇论文讨论广义金融资产供给及金融发展差异。全球金融危机后，研究进一步区分普通资产与在危机中仍能保值的安全资产。股票数量增加，不一定缓解对短期安全债务的需求。', '两种机制可以联系，但不能把 2006 年模型的全部资产都直接理解为无风险国债。安全属性、期限和流动性不同，会产生不同的定价与金融脆弱性。'] },
      { title: '均衡解释不等于不会发生危机', paragraphs: ['一个模型能够生成持续失衡，并不代表每一种支撑失衡的金融合同都安全。金融中介可能将资金配置到风险较高的资产，储蓄国也可能面临汇率与久期风险。', '现实的外部调整还取决于财政、人口、生产率、住房投资、汇率安排和政策冲击。该研究提供一种资产供求机制，应用时需要与这些因素并列检验，不能由“存在均衡”推出失衡没有代价。'] },
    ],
    sources: [{ title: '原论文：NBER 工作论文 11996', url: 'https://www.nber.org/papers/w11996', note: '2006 年工作论文，2008 年发表于 American Economic Review，98(1)，358–393。以下短摘为作者模型中的地区差异。', quote: "heterogeneity in these regions' capacity to generate financial assets from real investments.", translation: '这些地区把实际投资转化为金融资产的能力存在差异。' }],
    related: ['lucas-paradox', 'safe-assets', 'international-intermediation', 'intertemporal-account'],
  },
  {
    id: 'macroprudential', year: 2010, yearLabel: '2010 · 2011 定量扩展',
    title: '宏观审慎政策与借贷外部性', authors: 'Olivier Jeanne · Anton Korinek · Javier Bianchi',
    originalTitle: 'Excessive Volatility in Capital Flows: A Pigouvian Taxation Approach', kind: 'theory',
    question: '每个借款者都按自身利益行事，为什么整体经济仍可能借得过多？',
    lessonIds: ['globalization', 'governance', 'crisis', 'policy'], terms: ['宏观审慎', '借贷外部性', '抵押品约束', '庇古税'],
    sections: [
      { title: '个体风险与系统风险', paragraphs: ['单个企业借款时，会计算利息、收入和自身违约风险，却通常不会考虑自己的借贷选择怎样影响危机中所有人的抵押品价格。若许多企业同时扩张杠杆，未来被迫出售资产时，整体价格反应可能很大。', 'Jeanne 与 Korinek 从去杠杆周期的外部性出发分析预防性资本流动管理。Bianchi 的研究进一步使用小型开放经济模型，定量比较分散决策与受约束社会最优配置。'] },
      { title: '抵押品价格进入借款上限', paragraphs: ['如果可以借入的金额与抵押品市场价值相连，资产价格下降会直接压低融资上限。企业为了偿债而出售资产，又进一步压低价格。融资收缩与价格下降由此相互强化。', '个体把市场价格看作给定，未充分考虑自己今天多借一些，会怎样增加明天系统性出售的规模。其他借款者的融资额度同时受到影响，这就产生了借贷的外部成本。'] },
      { title: '为什么政策可能在繁荣期收紧', paragraphs: ['在模型中，预先提高脆弱融资的边际成本，可以减少未来约束收紧时的债务规模。税费、抵押率限制或资本缓冲等工具，分别影响借款需求、担保条件和金融机构承受损失的能力。', '合适的力度取决于约束未来绑定的概率、价格反馈大小与借款的真实收益。它不是要求所有跨境借贷都越少越好，而是使私人决策更充分地计入社会成本。'] },
      { title: '什么情况下外部性解释才成立', paragraphs: ['价格变化在通常的完整市场中只是买卖双方的收入转移，不一定需要干预。这里之所以会影响效率，是因为价格同时进入融资约束，并且参与者无法用完整合同事先分担风险。', '如果主要问题来自外部性以外的财政、信息或执行困难，简单套用同一税率就可能无效。政策还可能引发绕道融资、期限替代和风险转移，工具设计必须与具体约束匹配。'] },
      { title: '危机前预防与危机中救助', paragraphs: ['危机中的流动性支持、资产购买和债务重组，主要减轻已经出现的约束；危机前的审慎安排改变未来暴露。两者会相互影响：如果借款者预期总会获得救助，可能增加事前风险承担。', '课程中可以先观察回购折扣上升怎样造成融资缺口，再比较预先降低杠杆与事后注入流动性的效果。政策评估需要记录投资损失、危机概率和最终由谁承担成本。'] },
    ],
    sources: [{ title: '原论文：Jeanne 与 Korinek，2010', url: 'https://www.nber.org/papers/w15927', note: '同期发表于 American Economic Review Papers and Proceedings。', quote: 'In our model, capital controls reduce macroeconomic volatility and increase standard measures of consumer welfare.', translation: '在我们的模型中，资本管制降低宏观经济波动，并提高标准度量下的消费者福利。' }, { title: '定量研究：Overborrowing and Systemic Externalities in the Business Cycle', url: 'https://pubs.aeaweb.org/doi/10.1257/aer.101.7.3400', note: 'Javier Bianchi，American Economic Review，2011。' }],
    formulas: [{ expression: String.raw`B_{t+1}\leq\kappa q_t K_t`, explanation: '抵押约束的简化表示：B 为借款，qK 为抵押品价值，κ 为可抵押比例。q 下跌会降低融资上限；这是机制示意，并非所有论文统一使用的原式。' }],
    figure: 'repo-liquidity', related: ['sudden-stop', 'third-crisis', 'global-cycle', 'bank-runs'],
  },
  {
    id: 'global-cycle', year: 2013, yearLabel: '2013 演讲 · 2015 工作论文',
    title: '全球金融周期与政策独立性', authors: 'Hélène Rey',
    originalTitle: 'Dilemma not Trilemma: The Global Financial Cycle and Monetary Policy Independence', kind: 'theory',
    question: '汇率已经浮动，为什么国内信贷与资产价格仍受全球金融条件影响？',
    lessonIds: ['policy', 'regimes', 'dollar', 'globalization'], terms: ['全球金融周期', '二元悖论', '全球银行杠杆', '金融条件'],
    sections: [
      { title: '从三难到金融条件', paragraphs: ['三元悖论讨论固定汇率、资本自由流动与货币政策独立的约束。采用浮动汇率可以让本国短期政策利率不必机械跟随中心国家，但居民和企业面对的融资条件还包括长期收益率、信用利差和可获得的贷款规模。', 'Rey 在 2013 年 Jackson Hole 演讲、后以 2015 年工作论文发布的研究中，强调资本流动、资产价格与信贷具有共同的全球波动成分。需要把政策利率独立和整体金融条件独立区别开来。'] },
      { title: '风险偏好与中介杠杆', paragraphs: ['国际银行和投资者在多个市场共同配置资产。风险承受意愿增加时，他们可能同时增加杠杆、扩大跨境贷款和购买风险资产；风险厌恶上升时，又会共同缩减头寸。', '中心国家的货币政策能够通过资金成本、估值和中介资产负债表影响这个过程。汇率变化会重新分配风险，但不能自动切断全球机构的共同融资与风险管理。'] },
      { title: '“二元悖论”提出了什么判断', paragraphs: ['Rey 据此主张，在资本自由流动时，仅有浮动汇率不足以保证国内金融条件自主，资本账户管理与审慎政策可能成为额外工具。其论点针对跨境信贷和风险承担的传递渠道。', '这一主张具有明确的经验与政策争议。不能把它简化为“浮动汇率毫无作用”，也不能仅凭各国资产价格一起波动，就证明本国央行无法调整政策。共同冲击与跨境因果传递需要分别识别。'] },
      { title: '与反方证据怎样比较', paragraphs: ['讲义同时介绍了另一组证据：浮动经济体虽然仍受全球周期影响，利率和金融条件对中心国家的跟随通常弱于钉住经济体。汇率弹性可以提供缓冲，缓冲也可能不完全。', '两种观察可以同时成立。检验时要先确定考察的是短期政策利率、长期融资成本、银行信贷还是资产价格，再比较相似经济体在同一外部冲击下的反应。'] },
      { title: '政策工具针对哪条通道', paragraphs: ['贷款价值比、资本缓冲与杠杆限制主要影响国内金融机构承担风险的能力；资本流动措施针对部分跨境交易；外汇干预改变汇率路径与官方资产负债表。各工具作用环节不同，成本也不同。', '分析某项工具是否有效，需要检查它是否减轻了目标风险，还是仅把融资转移到其他机构或市场。全球周期研究扩大了政策分析的范围，也要求更细致地观察部门资产负债表。'] },
      { title: '把一项外部冲击分成几条路径', paragraphs: ['设中心国家意外收紧货币政策。第一条路径是利差与汇率：本国资产相对吸引力变化，引起资本流动和汇率调整。第二条路径是美元债务：汇率变化使部分借款者的净资产下降，贷款需求和信用风险随之改变。', '第三条路径经过国际中介。共同贷款人的融资成本或风险限额变化后，可能同时缩减对多个国家的授信。即使某国没有维持固定汇率，国内银行仍可能因为外部融资减少而提高贷款利率。第四条路径是风险资产估值，抵押品价格下跌进一步收紧融资。', '如果只观察本国央行没有跟随加息，就会遗漏后三条路径；如果只观察本国股价下跌，也无法据此断言政策利率丧失自主性。应分别记录政策利率、实际融资成本、跨境信贷、杠杆和汇率变化。', '因果识别还需要确定收紧是否真正出乎市场预期，以及同期是否出现全球增长消息。统计上提取到共同因子，只能说明波动具有共同部分；它本身不能证明所有变化都由某一家央行引起。'] },
      { title: '与课程政策图怎样对读', paragraphs: ['课程的 IS–LM–FX 图提供利差、产出与汇率的短期比较基准。全球金融周期研究还需要加入共同贷款人、风险溢价和中介约束；单一均衡图无法代替这些跨国数据和动态识别。'] },
    ],
    sources: [{ title: '原论文：Dilemma not Trilemma', url: 'https://www.nber.org/papers/w21162', note: '2013 年 Jackson Hole 演讲；2015 年 NBER 工作论文，2018 年修订。', quote: 'There is a global financial cycle in capital flows, asset prices and in credit growth.', translation: '资本流动、资产价格与信贷增长存在全球金融周期。' }, { title: '作者后续论述：国际货币政策传递', url: 'https://www.nber.org/papers/w21852', note: 'Rey，2016。区分货币政策冲击与金融条件的传递。' }],
    related: ['mundell-fleming', 'fear-floating', 'macroprudential', 'funding-cip'],
  },
  {
    id: 'funding-cip', year: 2015, yearLabel: '2015 初稿 · 2017 工作论文 · 2018 期刊',
    title: '抛补利率平价偏离与中介约束', authors: 'Wenxin Du · Alexander Tepper · Adrien Verdelhan',
    originalTitle: 'Deviations from Covered Interest Rate Parity', kind: 'puzzle',
    question: '已经锁定汇率的收益差，为什么没有被套利立即消除？',
    lessonIds: ['short-run', 'fx-market', 'dollar', 'crisis'], terms: ['交叉货币基差', '抛补利率平价偏离', '美元融资', '资产负债表成本'],
    sections: [
      { title: '无套利关系的比较对象', paragraphs: ['从一单位本币出发，可以直接投资本币存款，也可以按即期汇率换成外币、投资外币存款，并用远期合约锁定到期换回本币的价格。如果期限、信用与可交易条件一致，两条路径应给出相同的无风险到期收入。', '抛补利率平价由此给出即期、远期和利率之间的关系。它不依赖对未来即期汇率的猜测，与未抛补平价的预期收益条件不同。'] },
      { title: '危机后持续的偏离', paragraphs: ['Du、Tepper 与 Verdelhan 记录主要货币市场中持续的抛补平价偏离，特别关注危机后银行资产负债表成本与季末报告时点。原稿始于 2015 年，工作论文于 2017 年发布，2018 年正式发表。', '观察偏离必须先核对利率口径。银行无担保融资利率、国债收益率与有抵押利率具有不同的信用和流动性属性；政府债券的收益差还可能包含便利收益，不能全部视为相同的套利机会。'] },
      { title: '套利为什么占用稀缺资源', paragraphs: ['套利者需要融资、建立现货与远期头寸，并承担交易对手和结算安排。即使汇率风险已锁定，银行资产规模、资本占用、抵押品和内部风险限额仍会约束交易。', '当收益差低于使用资产负债表的边际成本时，继续扩大头寸不再有吸引力。季末的资产负债表收缩使这一成本更明显。价格之间的偏离因而可以持续，而不是所有参与者都忽略了同一个机会。'] },
      { title: '对冲需求决定压力方向', paragraphs: ['持有美元资产、以本币融资的机构可能通过外汇掉期取得美元；以美元融资后换成本币使用的机构则可能提供相反方向的需求。若两侧自然交易量不匹配，中介需要承担剩余头寸。', '中介承接能力下降时，满足同样规模的美元需求会变得更贵。讲义因此把交叉货币基差同时视为融资和对冲需求、以及中介承接能力的结果，不能由基差变化只推断一个原因。'] },
      { title: '怎样读中央银行流动性支持', paragraphs: ['央行货币互换与其他美元流动性安排，可以缓解部分机构的融资压力。但供给资格、期限、抵押品和价格决定它能覆盖哪些需求。市场基差收窄也需要与其他同期变化共同分析。', '课堂现金流图先展示无摩擦的等式，再加入买卖价差和资产负债表成本。这样可以区分理论上的毛收益差、交易成本之后的收益，以及实际可执行规模。'] },
      { title: '沿两条现金流检查报价', paragraphs: ['设即期汇率为每美元 7 元人民币，一年期人民币利率为 2%，美元利率为 4%。从 7 元人民币出发，直接存人民币，一年后得到 7.14 元；先换成 1 美元再存美元，一年后得到 1.04 美元。要让到期本币收入相同，理论远期汇率为 7.14/1.04，约为每美元 6.8654 元。', '若可实际成交的远期卖出美元价格是 6.95，外币路径可锁定 7.228 元收入，相对 7.14 元多出 0.088 元。这只是简化比较中的毛收益差，还没有证明某个投资者能够借到相同利率的资金并按相同价格成交。', '真正执行时，应将借入利率与存出利率分开，用即期买入外币的卖价和远期卖出外币的买价计算，还需计入手续费、抵押品占用和融资期限是否匹配。银行可能发现，毛收益不足以补偿新增头寸占用的资本。', '若两条路径的资产具有不同的违约概率，就更不能把全部收益差称为无风险套利。现金流核算让我们知道差额在哪里；对交易条件和中介约束的分析，才能解释差额为什么存在。'] },
    ],
    sources: [{ title: '原论文：Deviations from Covered Interest Rate Parity', url: 'https://www.nber.org/papers/w23170', note: '页面注明首稿为 2015 年 11 月；2018 年发表于 The Journal of Finance。', quote: 'The CIP deviations also appear significantly correlated with other fixed-income spreads and with nominal interest rates.', translation: '抛补利率平价偏离还与其他固定收益利差及名义利率显著相关。' }],
    formulas: [{ expression: String.raw`1+i_{\mathrm{home}}=\frac{F}{S}(1+i_{\mathrm{foreign}})`, explanation: 'S、F 均为一单位外币的本币价格，利率对应同一期限。忽略交易成本且两边信用、流动性可比时成立。' }],
    figure: 'cip-cashflow', related: ['interest-parity', 'forward-premium', 'global-cycle', 'safe-assets'],
  },
  {
    id: 'safe-assets', year: 2016, yearLabel: '2016 模型 · 2017 系统论述',
    title: '安全资产短缺', authors: 'Ricardo Caballero · Emmanuel Farhi · Pierre-Olivier Gourinchas',
    originalTitle: 'Safe Asset Scarcity and Aggregate Demand / The Safe Assets Shortage Conundrum', kind: 'theory',
    question: '全球储蓄增加时，为什么安全资产的供给可能跟不上需求？',
    lessonIds: ['dollar', 'future', 'crisis', 'sovereign-debt'], terms: ['安全资产短缺', '便利收益', '安全陷阱', '储备资产'],
    sections: [
      { title: '安全是一项特殊服务', paragraphs: ['居民需要应急和养老资产，银行需要抵押品，官方机构需要储备。一项资产若在市场承压时仍较容易变现、保值，就能提供普通收益以外的服务。Caballero、Farhi 与 Gourinchas 以系统性不利事件中保持价值的债务工具作为安全资产的操作性定义。', '这里的安全具有相对性。名义偿付、实际购买力和外币价值是不同维度，长期国债也可能有明显的利率风险。不能因资产被称为安全，就忽略计价货币和持有期限。'] },
      { title: '供求缺口怎样影响收益率', paragraphs: ['如果需要持有安全资产的财富增长快于可信供给，在其他条件不变时，投资者愿意支付更高价格、接受更低收益。这种对安全性、流动性和抵押用途的需求，可以形成便利收益。', '安全供给不能仅靠给普通债务贴上标签来增加。财政能力、法律承诺、市场深度及危机中的支付能力，决定投资者是否愿意相信其安全属性。'] },
      { title: '私人创造安全资产的风险', paragraphs: ['金融机构可以把贷款打包、分层，用优先级债券向投资者提供看似较安全的现金流。但分层只能重新分配损失，不能消除底层资产的总风险；相关性和尾部损失若被低估，安全地位就可能在危机中突然消失。', '这时资产供给和需求可能同时恶化：被认为安全的私人资产减少，投资者又更急于转向少数可信资产，价格和融资压力便会集中变化。'] },
      { title: '安全陷阱的机制', paragraphs: ['在名义利率等约束使安全收益率难以进一步下降的环境中，价格不能充分调整来平衡供求。模型中，产出和收入下降会压低资产需求，经济可能通过衰退完成调整。开放经济中的资金流动还会把压力传到其他国家。', '这一结论依赖利率约束、价格调整与资产需求的设定。它不意味着安全资产在所有时期都短缺，也不能单独解释任何一次利率下降。'] },
      { title: '公共供给与财政信用', paragraphs: ['政府可以发行债务满足需求，但供给过多又可能削弱财政信用；关键是未来税收、支出和政策承诺能否支持偿付。安全性与数量之间可能存在约束。', '提供国际安全资产也不等于发行国必须每年出现经常账户逆差。经常账户记录净借贷，全球安全债务供给还涉及总资产负债规模、私人发行和资产交换。讨论储备货币地位时，应同时看财政信誉与金融结构。'] },
    ],
    sources: [{ title: '模型原文：Safe Asset Scarcity and Aggregate Demand', url: 'https://www.nber.org/papers/w22044', note: '2016 年工作论文，讨论总需求与开放经济中的安全陷阱。' }, { title: '原作者系统论述：The Safe Assets Shortage Conundrum', url: 'https://www.aeaweb.org/articles?id=10.1257%2Fjep.31.3.29', note: 'Journal of Economic Perspectives，2017，31(3)，29–46。', quote: 'A safe asset is a simple debt instrument that is expected to preserve its value during adverse systemic events.', translation: '安全资产是一种简单债务工具，人们预期它在系统性不利事件中仍能保持价值。' }],
    related: ['global-imbalances', 'triffin', 'international-intermediation', 'funding-cip'],
  },
  {
    id: 'dominant-currency', year: 2016, yearLabel: '2016 工作论文 · 2020 期刊',
    title: '主导货币定价', authors: 'Gita Gopinath · Emine Boz · Camila Casas · Federico Díez · Pierre-Olivier Gourinchas · Mikkel Plagborg-Møller',
    originalTitle: 'Dominant Currency Paradigm', kind: 'theory',
    question: '两国都不是美国，它们之间的贸易为什么仍受美元汇率影响？',
    lessonIds: ['dollar', 'long-run', 'enterprise', 'policy'], terms: ['主导货币定价', '美元计价', '汇率传递', '贸易条件'],
    sections: [
      { title: '合同究竟用哪一种货币定价', paragraphs: ['传统模型常设出口商以生产者本币定价，或以进口国货币定价。现实中，大量贸易合同使用美元等少数货币，即使交易双方都不属于该货币发行国。', 'Gopinath 等人的主导货币范式将这种定价方式放入开放经济模型，并结合企业和双边贸易数据检验。工作论文发表于 2016 年，正式论文发表于 2020 年《美国经济评论》。'] },
      { title: '价格黏性为什么重要', paragraphs: ['如果合同的美元价格在一段时间内不变，进口国货币对美元贬值，就会直接抬高本币进口价格。出口国货币对进口国货币的双边汇率变化，未必是短期价格传递的主要解释变量。', '例如两家非美国企业以美元订立合同。进口国货币对美元贬值，而出口国货币不变时，进口方成本上升；若出口国货币对美元贬值，出口方本币收入上升，却不一定立即降低买方支付的美元价格。'] },
      { title: '进口投入与竞争者定价', paragraphs: ['出口企业可能需要进口中间品。本币贬值提高本币销售收入时，也可能提高投入成本，利润和出口数量的净变化取决于进口含量。', '企业还会参考竞争者的价格：若竞争者普遍以美元维持稳定报价，单个企业也可能不愿频繁改变美元价格。这种定价互补与进口投入一起，使主导货币的作用延伸到整个贸易网络。'] },
      { title: '贬值何时能够扩大出口', paragraphs: ['在主导货币价格暂时固定时，出口国贬值可能主要改变企业利润，而非立即降低外国买方价格。随着企业重新定价、生产和数量调整，较长期的反应可能不同。', '因此，主导货币定价并不否认所有支出转换效应。它要求说明观察期限、合同货币、价格重设频率与投入结构，才能判断传统贬值促进出口的通道有多强。'] },
      { title: '全球贸易与货币政策', paragraphs: ['当多国货币同时对美元贬值时，非美国贸易中的进口成本也可能普遍上升。这使美元变化具有超出美国双边贸易份额的影响。原论文用跨国与企业数据检验这一机制。', '制度含义也不能只由单个企业的计价选择推出。企业选择美元可能降低其局部交易成本，却使整个经济更暴露于美元冲击；改变计价方式需要市场、融资与对冲条件共同支持。'] },
      { title: '用同一份合同比较三种定价', paragraphs: ['设一家中国企业向日本销售商品，合同价格暂不调整。若合同定为 100 美元，人民币对美元贬值会提高出口商收到的人民币，但日本买方的日元支出由日元对美元汇率决定。人民币对日元的双边变化，不能单独告诉我们买方价格如何变化。', '若改为固定人民币价格，人民币对日元贬值会直接降低日本买方的日元价格，这更接近生产者货币定价下的支出转换。若改为固定日元价格，日本买方短期价格不变，汇率风险先落在出口企业利润上。这更接近目的地货币定价。', '再加入进口投入：企业需要购买 40 美元的原料。在美元售价与美元投入价格不变时，它的美元毛现金差额仍为 60。人民币贬值同时提高收入和投入成本，不能把人民币销售收入的全部增加都当成利润增加。', '等到企业可以重新报价，竞争者价格、需求弹性和生产成本才会进一步改变美元售价与数量。上述比较说明，识别汇率传递需要合同货币和重设时点，只有月度总出口金额往往不足以区分三种机制。'] },
      { title: '计价选择本身也需要解释', paragraphs: ['主导货币份额并非永久不变的外生常数。企业规模、竞争者报价、进口投入和融资货币都会影响选择。比较不同国家时，还要区分贸易报价、发票计价和实际支付所使用的货币，这些统计口径不能直接互换。'] },
    ],
    sources: [{ title: '原论文：American Economic Review，2020', url: 'https://www.aeaweb.org/articles?id=10.1257%2Faer.20171201', note: '110(3)，677–719；正式发表版本。' }, { title: '首发工作论文：NBER 22943', url: 'https://www.nber.org/papers/w22943', note: '2016 年工作论文，2019 年修订。', quote: 'Most trade is invoiced in very few currencies.', translation: '大部分贸易以极少数几种货币开票。' }],
    formulas: [{ expression: String.raw`P_{\mathrm{import}}^{\mathrm{LC}}=S_{\mathrm{LC/USD}}\,P^{\mathrm{USD}}`, explanation: '当美元合同价格暂时固定时，本币/美元汇率上升会直接提高本币进口价格；尚未计入税费、加价调整等因素。' }],
    related: ['currency-networks', 'new-open-macro', 'elasticities', 'balassa-samuelson'],
  },
  {
    id: 'digital-currency', year: 2019, yearLabel: '2019',
    title: '数字货币、平台与货币区域', authors: 'Markus Brunnermeier · Harold James · Jean-Pierre Landau',
    originalTitle: 'The Digitalization of Money', kind: 'theory',
    question: '数字支付与平台网络，会怎样改变货币竞争和跨境使用？',
    lessonIds: ['digital-money', 'future', 'sanctions', 'renminbi'], terms: ['数字货币区域', '数字美元化', '货币职能分离', '平台货币'],
    sections: [
      { title: '从货币职能看数字化', paragraphs: ['计价单位、支付媒介和价值储藏可以由不同安排承担。数字技术降低转换和支付成本，可能使人们用一种资产储值、另一种工具支付，同时仍用法定货币标价。', 'Brunnermeier、James 与 Landau 在 2019 年讨论这种职能分离及其对货币竞争的影响。论文属于制度与理论分析，提出可能的机制和情景；它并未预言所有国家都会采用同一种数字货币制度。'] },
      { title: '平台为什么可能重新把服务捆在一起', paragraphs: ['大型平台可以把支付与购物、通信、身份和数据服务结合。用户选择某种支付工具，可能因为它与常用服务相连。平台规模扩大又提高该工具对商家的吸引力。', '这种网络便利也可能带来转换成本和互操作障碍。如果用户必须留在同一平台才能方便支付，货币竞争就与平台市场结构联系起来。观察技术性能之外，还要看进入、退出和兑换条件。'] },
      { title: '数字货币区域与国家边界', paragraphs: ['传统货币区域通常与国家疆域、法律和税收安排联系较紧。跨境数字平台则可能把不同国家的用户连接在同一支付生态中，形成与地理边界不完全重合的使用范围。', '如果这一生态以外国货币计价、结算或作为储备，本国居民可能增加对外国货币的依赖，即论文讨论的数字美元化。使用电子钱包本身并不等于美元化，关键是钱包中的债权究竟以什么计价、由谁兑现。'] },
      { title: '稳定币与央行数字货币的债权区别', paragraphs: ['银行存款、私人稳定币和央行数字货币即使界面相似，背后的债权也不同。应分别检查发行人、储备资产、赎回承诺、清算安排和损失承担者。技术记录方式不能替代这些资产负债关系。', '承诺固定面值赎回、却持有流动性不足资产的私人工具，可能面对集中赎回压力。央行数字货币涉及公共货币的可得性，也可能影响银行负债和跨境资金转移；具体效果取决于持有范围、付息与额度等设计。'] },
      { title: '跨境便利与宏观约束', paragraphs: ['更便宜、更快速的支付能够降低部分交易成本，但货币兑换、身份核验、流动性与最终结算仍需制度安排。跨境连接还可能加快资金流动，使货币替代或危机中的资产转移更迅速。', '评价数字货币应把支付效率、资产安全和货币主权分别分析。货币网络理论、挤兑模型及资本流动约束仍然适用，数字技术改变了部分成本和速度，并未取消金融合同与宏观预算约束。'] },
    ],
    sources: [{ title: '原论文：The Digitalization of Money', url: 'https://www.nber.org/papers/w26300', note: '2019 年 NBER 工作论文 26300；作者讨论货币职能、平台与跨境货币区域。', quote: 'We may see an unbundling of the separate roles of money, creating fiercer competition among specialized currencies.', translation: '我们可能看到货币的不同职能相互分离，使各具专门用途的货币之间竞争加剧。' }],
    related: ['currency-networks', 'bank-runs', 'dominant-currency', 'safe-assets'],
  },
]
